project_id = "outlast-51-family-league"

[auth]
enabled = true
site_url = "https://survivor-fan-game.vercel.app"
additional_redirect_urls = ["https://survivor-fan-game.vercel.app/auth/callback"]
enable_signup = true
minimum_password_length = 6

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
max_frequency = "1m"
otp_length = 8
otp_expiry = 3600

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
