"use client";

import { useEffect,useState } from "react";
import Image from "next/image";
import { Countdown } from "../components/Countdown";
import { profileIcon } from "../profile-icons";

type Castaway={id:string;name:string;tribe:string;image:string;status:string};
type Percent={value:string;count:number;percent:number};
type SeasonPick={stage:"opening"|"waiting"|"repick"|"locked";originalId:string;originalName:string|null;endgameId:string;endgameName:string|null;switched:boolean;individualGamePoints:number;endgamePoints:number;repickClosesAt:string|null;updatedAt:string|null};
type LeagueData={joined:boolean;profile?:{displayName:string;teamName:string;immunityStreak:number};episode:{id:number;title:string;airAt:string;lockAt:string;phase:string;bonusQuestion:string;bonusOptions:string[]};castaways:Castaway[];pick?:{favoriteId:string;immunityPick:string;bootPick:string;bonusPick:string;shotInTheDark:string;carriedFromEpisodeId:number|null;updatedAt:string};seasonPick:SeasonPick;leaderboard:{id:string;rank:number;name:string;teamName:string;avatarKey:string;points:number;badges:string[]}[];locked:boolean;preseasonLocked:boolean;pickPercentages:null|Record<string,Percent[]>;pendingReveal?:{id:number;title:string;revealAt:string};shotInTheDarkAvailable:boolean};

export function PlayClient(){
 const[data,setData]=useState<LeagueData|null>(null),[error,setError]=useState(""),[saving,setSaving]=useState(false),[saveConfirmation,setSaveConfirmation]=useState("");
 const[favorite,setFavorite]=useState(""),[immunity,setImmunity]=useState(""),[boot,setBoot]=useState(""),[bonus,setBonus]=useState(""),[shot,setShot]=useState(""),[openingPick,setOpeningPick]=useState(""),[endgamePick,setEndgamePick]=useState(""),[endgameSaving,setEndgameSaving]=useState(false),[endgameMessage,setEndgameMessage]=useState("");
 const load=()=>fetch("/api/league").then(async response=>{if(!response.ok){setError("The league could not load.");return}const next=await response.json() as LeagueData;setData(next);setFavorite(next.pick?.favoriteId||"");setImmunity(next.pick?.immunityPick||"");setBoot(next.pick?.bootPick||"");setBonus(next.pick?.bonusPick||"");setShot(next.pick?.shotInTheDark||"");setOpeningPick(next.seasonPick?.originalId||"");setEndgamePick(next.seasonPick?.endgameId||"")});
 useEffect(()=>{load()},[]);
 if(error&&!data)return <div className="notice">{error}</div>;
 if(!data)return <div className="loading"><p className="eyebrow">Setting up camp…</p></div>;
 if(!data.joined)return <JoinForm onJoined={load}/>;

 async function save(){setSaving(true);setError("");setSaveConfirmation("");const response=await fetch("/api/picks",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({episodeId:data?.episode.id,favoriteId:favorite,immunityPick:immunity,bootPick:boot,bonusPick:bonus,shotInTheDark:shot,individualGamePick:openingPick})});const body=await response.json() as {error?:string;updatedAt?:string};setSaving(false);if(!response.ok){setError(body.error||"Picks were not saved.");return}setSaveConfirmation(body.updatedAt||new Date().toISOString());await load()}
 async function saveEndgame(){setEndgameSaving(true);setEndgameMessage("");const response=await fetch("/api/endgame-pick",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({castawayId:endgamePick})});const body=await response.json() as {error?:string};setEndgameSaving(false);if(!response.ok){setEndgameMessage(body.error||"Your Final Torch pick was not saved.");return}setEndgameMessage("✓ Final Torch pick saved");await load()}

 const complete=Boolean(favorite&&immunity&&boot&&(openingPick||data.preseasonLocked));
 const dirty=!data.pick||favorite!==data.pick.favoriteId||immunity!==data.pick.immunityPick||boot!==data.pick.bootPick||bonus!==data.pick.bonusPick||shot!==data.pick.shotInTheDark||(!data.preseasonLocked&&openingPick!==data.seasonPick.originalId);
 const endgameDirty=endgamePick!==data.seasonPick.endgameId;
 const lastSavedAt=saveConfirmation||data.pick?.updatedAt||"";
 const name=(id:string)=>data.castaways.find(c=>c.id===id)?.name||id;
 const choice=(value:string)=>value?name(value):"No pick yet";
 const immunityChoice=immunity?(data.episode.phase==="individual"?choice(immunity):immunity):"No pick yet";
 const shotChoice=shot==="immunity"?`Immunity Pick · ${immunityChoice}`:shot==="boot"?`Vote-Out Pick · ${choice(boot)}`:shot==="bonus"?`Play Your Advantage · ${bonus||"No pick yet"}`:"Saved for a later episode";
 const savedLabel=lastSavedAt?`Last saved ${new Date(lastSavedAt).toLocaleString("en-US",{weekday:"long",month:"long",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit",timeZone:"America/Detroit"})} ET`:"";

 return <><div className="play-grid"><div>
  {data.pendingReveal&&<div className="notice"><strong>Episode {data.pendingReveal.id} results are spoiler-protected.</strong><span>Scores and eliminations reveal automatically {new Date(data.pendingReveal.revealAt).toLocaleString("en-US",{weekday:"long",hour:"numeric",minute:"2-digit",timeZone:"America/Detroit"})} ET.</span></div>}
  {data.pick?.carriedFromEpisodeId&&<div className="notice"><strong>Your Episode {data.pick.carriedFromEpisodeId} picks carried forward.</strong><span>Review each named pick below and change anything you want before the deadline.</span></div>}
  <div className="notice"><strong>Weekly Favorite, Immunity, and Vote-Out Picks are required.</strong><span>Play Your Advantage and Shot in the Dark are optional.</span></div>

  <section className="panel"><div className="panel-title"><div><p className="eyebrow">Required weekly pick · 1 point · +1 underdog bonus</p><h2>Weekly Favorite Pick</h2></div><span className="status-pill">{favorite?"Picked":"Needed"}</span></div><p className="pick-help">Choose one active castaway to survive this episode. If fewer than 20% of submitted favorites choose the same person and they survive, you earn an extra point.</p><div className="pick-options">{data.castaways.map(c=><div className={`pick-option ${c.tribe.toLowerCase()}`} key={c.id}><input aria-label={`Choose ${c.name} as your Weekly Favorite Pick`} disabled={data.locked} checked={favorite===c.id} onChange={()=>setFavorite(c.id)} id={`fav-${c.id}`} name="favorite" type="radio"/><label htmlFor={`fav-${c.id}`}><span className="avatar"><Image src={c.image} alt="" width={38} height={38}/></span><span><strong>{c.name}</strong><small>{c.tribe==="Unassigned"?"Tribe TBA":c.tribe}</small></span></label></div>)}</div><PickReceipt label="Weekly Favorite Pick" value={choice(favorite)}/></section>

  <section className="panel prediction-panel"><div className="panel-title"><div><p className="eyebrow">Required weekly pick · 2 points</p><h2>Immunity Pick</h2></div><span className="status-pill">{immunity?"Picked":"Needed"}</span></div><p className="pick-help">Who will win {data.episode.phase==="individual"?"individual":"tribal"} immunity this episode?</p>{data.episode.phase==="individual"?<CastSelect id="immunity" label="Immunity Pick" value={immunity} setValue={setImmunity} cast={data.castaways} disabled={data.locked}/>:<div className="tribe-picks">{["Savu","Toka"].map(tribe=><div className={`tribe-choice ${tribe.toLowerCase()}`} key={tribe}><input aria-label={`Choose ${tribe} as your Immunity Pick`} disabled={data.locked} checked={immunity===tribe} onChange={()=>setImmunity(tribe)} id={`tribe-${tribe}`} name="immunity" type="radio"/><label htmlFor={`tribe-${tribe}`}><small>TRIBE</small><h3>{tribe}</h3></label></div>)}</div>}<PickReceipt label="Immunity Pick" value={immunityChoice}/></section>

  <div className="prediction-grid"><section className="panel"><p className="eyebrow">Required weekly pick · 3 points</p><h2>Vote-Out Pick</h2><p className="pick-help">Who will be voted out at Tribal Council? Quits and medical removals do not count.</p><CastSelect id="boot" label="Vote-Out Pick" value={boot} setValue={setBoot} cast={data.castaways} disabled={data.locked}/><PickReceipt label="Vote-Out Pick" value={choice(boot)}/></section><section className="panel"><p className="eyebrow">Optional weekly pick · +1 / −1 point</p><h2>Play Your Advantage</h2><p className="pick-help">Watch the official previews for an edge on this week’s question.</p><p className="pick-help"><strong>{data.episode.bonusQuestion}</strong></p><p className="pick-help">Correct: +1 point. Wrong: −1 point. Skip: 0 points. Choose fresh each week; this pick does not carry forward.</p><div className="bonus-options">{data.episode.bonusOptions.map(option=><button type="button" disabled={data.locked} aria-pressed={bonus===option} className={bonus===option?"selected":""} onClick={()=>setBonus(option)} key={option}>{option}</button>)}<button type="button" disabled={data.locked} aria-pressed={!bonus} className={`skip-option ${!bonus?"selected":""}`} onClick={()=>{setBonus("");if(shot==="bonus")setShot("")}}>Skip · 0 points</button></div><PickReceipt label="advantage answer" value={bonus||"Skipped · 0 points"}/></section></div>

  <SeasonPickPanel data={data} openingPick={openingPick} setOpeningPick={setOpeningPick} endgamePick={endgamePick} setEndgamePick={setEndgamePick} saveEndgame={saveEndgame} saving={endgameSaving} dirty={endgameDirty} message={endgameMessage}/>

  <section className="panel double-card"><div><p className="eyebrow">Optional advantage · one use all season</p><h2>Shot in the Dark</h2><p>Play it on an Immunity Pick, Vote-Out Pick, or Play Your Advantage answer. If that pick is correct, you earn those points a second time. An incorrect Play Your Advantage answer still costs only 1 point. It is spent when the episode locks.</p></div><div><select aria-label="Choose which prediction gets your Shot in the Dark" disabled={data.locked||(!data.shotInTheDarkAvailable&&!shot)} value={shot} onChange={event=>setShot(event.target.value)}><option value="">Save it for later</option><option value="immunity">Immunity Pick</option><option value="boot">Vote-Out Pick</option><option value="bonus" disabled={!bonus}>Play Your Advantage</option></select><PickReceipt label="Shot in the Dark" value={shotChoice}/></div></section>

  <div className="save-bar sticky-save"><span className={`save-message ${saveConfirmation&&!dirty&&complete?"save-success":""}`} role="status" aria-live="polite">{error?<strong>{error}</strong>:lastSavedAt?<><strong>{!complete?"Required picks missing":dirty?"Unsaved changes":saveConfirmation?"✓ Picks saved successfully":"Picks on file"}</strong><small>{savedLabel}</small></>:!complete?(data.preseasonLocked?"Choose your Weekly Favorite, Immunity, and Vote-Out Picks to save.":"Choose your Weekly Favorite, Immunity, Vote-Out, and opening Outlast Picks to save."):"Your picks remain private until the deadline."}</span><button className="button button-primary" onClick={save} disabled={saving||data.locked||!complete}>{saving?"Saving…":data.locked?"Weekly picks locked":saveConfirmation&&!dirty?"Saved ✓":"Save all weekly picks"}</button></div>
 </div><aside><div className="deadline-box"><p className="eyebrow">Weekly picks lock in</p><Countdown target={data.episode.lockAt}/><p>{new Date(data.episode.lockAt).toLocaleString("en-US",{weekday:"long",month:"long",day:"numeric",hour:"numeric",minute:"2-digit",timeZone:"America/Detroit"})} ET</p></div><div className="panel leaderboard"><p className="eyebrow">Live standings</p><h2>Leaderboard</h2>{data.leaderboard.map(row=><div className="score-row" key={row.id}><span className="rank">{String(row.rank).padStart(2,"0")}</span><span className="avatar small" aria-label={`${profileIcon(row.avatarKey).label} icon`}>{profileIcon(row.avatarKey).symbol}</span><span className="leaderboard-name"><strong>{row.teamName||row.name}</strong>{row.teamName&&row.teamName!==row.name&&<small className="leaderboard-player">{row.name}</small>}{row.badges[0]&&<small className="badge">{row.badges[0]}</small>}</span><span className="score">{row.points}</span></div>)}</div>
  <div className="panel"><p className="eyebrow">Your Outlast journey</p><h2>Every point, explained.</h2><p className="pick-help">See how each episode’s points add to your running season total.</p><a className="text-link" href="/season">Open My Season →</a></div>
  {data.locked&&data.pickPercentages&&<div className="panel pulse"><p className="eyebrow">League pulse</p><h2>What everyone picked</h2>{[["Weekly Favorite","favorite_id"],["Immunity","immunity_pick"],["Vote-Out","boot_pick"]].map(([label,key])=><div key={key}><h3>{label}</h3>{data.pickPercentages![key].slice(0,4).map(percent=><div className="percent-row" key={percent.value}><span>{name(percent.value)}</span><strong>{percent.percent}%</strong></div>)}</div>)}</div>}
 </aside></div></>;
}

function SeasonPickPanel({data,openingPick,setOpeningPick,endgamePick,setEndgamePick,saveEndgame,saving,dirty,message}:{data:LeagueData;openingPick:string;setOpeningPick:(value:string)=>void;endgamePick:string;setEndgamePick:(value:string)=>void;saveEndgame:()=>Promise<void>;saving:boolean;dirty:boolean;message:string}){
 const season=data.seasonPick;
 if(season.stage==="opening")return <section className="panel season-picks"><div><p className="eyebrow">Required opening pick · 10 points</p><h2>Outlast Pick: Reach the Individual Game</h2><p>Choose one castaway before Episode 1 locks. You earn 10 points if your pick is still in the game when Jeff announces there are no more tribes and the game is individual—even if that castaway is voted out later in the same episode.</p></div><div><CastSelect id="opening-outlast" label="Opening Outlast Pick" value={openingPick} setValue={setOpeningPick} cast={data.castaways} disabled={data.preseasonLocked}/><PickReceipt label="Opening Outlast Pick" value={openingPick?data.castaways.find(c=>c.id===openingPick)?.name||openingPick:"No pick yet"}/></div></section>;
 if(season.stage==="waiting")return <section className="panel season-picks season-pick-status"><div><p className="eyebrow">Opening pick locked</p><h2>Outlast Pick: Reach the Individual Game</h2><p>Your pick stays in place until Jeff officially announces there are no more tribes and the game is individual. The one-time Final Torch decision opens after that episode’s spoiler-safe results reveal.</p></div><PickReceipt label="Your locked Outlast Pick" value={season.originalName||"No opening pick was submitted"}/></section>;
 if(season.stage==="repick"){const active=data.castaways.some(c=>c.id===endgamePick),selectedName=data.castaways.find(c=>c.id===endgamePick)?.name||season.endgameName||endgamePick||"No pick yet";return <section className="panel season-picks season-pick-repick"><div><p className="eyebrow">One-time decision · Final Torch Pick</p><h2>Keep your pick or switch?</h2><p>Your opening pick: <strong>{season.originalName||"No pick submitted"}</strong> · <strong>{season.individualGamePoints} of 10 points earned</strong>.</p><p>Keep your original active castaway for the full endgame award: 10 points to win or 3 points to reach the finale. Switch to any remaining castaway for half: 5 points to win or 1.5 points to reach the finale. Your earned individual-game points do not change.</p>{season.repickClosesAt&&<p className="repick-deadline">Decision locks {new Date(season.repickClosesAt).toLocaleString("en-US",{weekday:"long",month:"long",day:"numeric",hour:"numeric",minute:"2-digit",timeZone:"America/Detroit"})} ET.</p>}</div><div>{endgamePick&&!active&&<OptionHiddenWarning name={selectedName}/>}<CastSelect id="final-torch" label="Final Torch Pick" value={active?endgamePick:""} setValue={setEndgamePick} cast={data.castaways} disabled={false}/><PickReceipt label="Final Torch Pick" value={selectedName}/><p className="pick-value-note">{!endgamePick?"Choose a remaining castaway · half points":endgamePick===season.originalId&&active?"Keeping original · full points":"Switching castaways · half points"}</p>{message&&<p className="save-success" role="status">{message}</p>}<button type="button" className="button button-primary endgame-save" onClick={saveEndgame} disabled={saving||!endgamePick||!dirty}>{saving?"Saving…":dirty?"Save Final Torch Pick":"Final Torch Pick saved"}</button></div></section>}
 return <section className="panel season-picks season-pick-status"><div><p className="eyebrow">Final Torch decision locked</p><h2>Your Endgame Pick</h2><p>{season.switched?"You switched castaways, so this pick earns 5 points to win or 1.5 points to reach the finale.":"You kept your original castaway, so this pick earns 10 points to win or 3 points to reach the finale."}</p></div><div><PickReceipt label="Opening Outlast Pick" value={season.originalName||"No opening pick"}/><PickReceipt label="Final Torch Pick" value={season.endgameName||"No Final Torch pick"}/></div></section>;
}

function OptionHiddenWarning({name}:{name:string}){return <p className="pick-warning">{name} is no longer in the game. Choose a remaining castaway for your Final Torch Pick.</p>}
function PickReceipt({label,value}:{label:string;value:string}){return <p className="pick-receipt"><span>Your {label}</span><strong>{value}</strong></p>}
function CastSelect({id,label,value,setValue,cast,disabled}:{id:string;label:string;value:string;setValue:(value:string)=>void;cast:Castaway[];disabled:boolean}){return <select className="cast-select" id={id} aria-label={label} value={value} onChange={event=>setValue(event.target.value)} disabled={disabled}><option value="">Choose a castaway…</option>{cast.map(c=><option value={c.id} key={c.id}>{c.name} · {c.tribe==="Unassigned"?"Tribe TBA":c.tribe}</option>)}</select>}
function JoinForm({onJoined}:{onJoined:()=>Promise<void>}){const[name,setName]=useState(""),[team,setTeam]=useState(""),[inviteCode,setInviteCode]=useState(""),[busy,setBusy]=useState(false),[joinError,setJoinError]=useState("");async function join(event:React.FormEvent){event.preventDefault();setBusy(true);setJoinError("");const response=await fetch("/api/league",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({displayName:name,teamName:team,inviteCode})});setBusy(false);if(!response.ok){const body=await response.json().catch(()=>({}));setJoinError(body.error||"The league could not be joined. Try again.");return}await onJoined()}return <form className="join-card" onSubmit={join}><p className="eyebrow">One last step</p><h2>Join the tribe</h2><p>Use the account you just created and the league code Mike shared. Your picks stay private until the episode locks. Joining also signs you up for one spoiler-free pick reminder before each new episode.</p>{joinError&&<div className="notice">{joinError}</div>}<label htmlFor="name">Your name</label><input id="name" required maxLength={40} value={name} onChange={event=>setName(event.target.value)} placeholder="Mike"/><label htmlFor="team">Team name <small>(optional · must be unique)</small></label><input id="team" maxLength={50} value={team} onChange={event=>setTeam(event.target.value)} placeholder="The Torch Snuffers"/><label htmlFor="invite-code">League code</label><input id="invite-code" required maxLength={40} autoCapitalize="characters" value={inviteCode} onChange={event=>setInviteCode(event.target.value)} placeholder="Enter league code"/><button className="button button-primary" disabled={busy}>{busy?"Joining…":"Join the tribe →"}</button></form>}
