"use client";
import { useEffect,useState } from "react";
import { Countdown } from "../components/Countdown";
import { profileIcon } from "../profile-icons";
type Castaway={id:string;name:string;tribe:string;image:string;status:string};
type Percent={value:string;count:number;percent:number};
type LeagueData={joined:boolean;profile?:{displayName:string;teamName:string;winnerPick:string|null;immunityStreak:number};episode:{id:number;title:string;airAt:string;lockAt:string;phase:string;bonusQuestion:string;bonusOptions:string[]};castaways:Castaway[];pick?:{favoriteId:string;immunityPick:string;bootPick:string;bonusPick:string;doubleDown:string;carriedFromEpisodeId:number|null;updatedAt:string};leaderboard:{rank:number;name:string;teamName:string;avatarKey:string;points:number;badges:string[]}[];locked:boolean;preseasonLocked:boolean;pickPercentages:null|Record<string,Percent[]>;matchups:{a:{name:string;points:number};b:{name:string;points:number}|null}[];pendingReveal?:{id:number;title:string;revealAt:string};doubleDownAvailable:boolean};

export function PlayClient(){
 const[data,setData]=useState<LeagueData|null>(null),[error,setError]=useState(""),[saving,setSaving]=useState(false),[saveConfirmation,setSaveConfirmation]=useState("");const[favorite,setFavorite]=useState(""),[immunity,setImmunity]=useState(""),[boot,setBoot]=useState(""),[bonus,setBonus]=useState(""),[doubleDown,setDoubleDown]=useState(""),[winner,setWinner]=useState("");
 const load=()=>fetch("/api/league").then(async r=>{if(!r.ok){setError("The league could not load.");return}const d=await r.json() as LeagueData;setData(d);setFavorite(d.pick?.favoriteId||"");setImmunity(d.pick?.immunityPick||"");setBoot(d.pick?.bootPick||"");setBonus(d.pick?.bonusPick||"");setDoubleDown(d.pick?.doubleDown||"");setWinner(d.profile?.winnerPick||"")});useEffect(()=>{load()},[]);
 if(error&&!data)return <div className="notice">{error}</div>;if(!data)return <div className="loading"><p className="eyebrow">Setting up camp…</p></div>;if(!data.joined)return <JoinForm onJoined={load}/>;
 async function save(){setSaving(true);setError("");setSaveConfirmation("");const r=await fetch("/api/picks",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({episodeId:data?.episode.id,favoriteId:favorite,immunityPick:immunity,bootPick:boot,bonusPick:bonus,doubleDown,winnerPick:winner})});const body=await r.json() as {error?:string;updatedAt?:string};setSaving(false);if(!r.ok){setError(body.error||"Picks were not saved.");return}setSaveConfirmation(body.updatedAt||new Date().toISOString());await load()}
 const complete=favorite&&immunity&&(winner||data.preseasonLocked),dirty=!!data.pick&&(favorite!==data.pick.favoriteId||immunity!==data.pick.immunityPick||boot!==data.pick.bootPick||bonus!==data.pick.bonusPick||doubleDown!==data.pick.doubleDown||(!data.preseasonLocked&&winner!==(data.profile?.winnerPick||""))),lastSavedAt=saveConfirmation||data.pick?.updatedAt||"";const name=(id:string)=>data.castaways.find(c=>c.id===id)?.name||id;const savedLabel=lastSavedAt?`Last saved ${new Date(lastSavedAt).toLocaleString("en-US",{weekday:"long",month:"long",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit",timeZone:"America/Detroit"})} ET`:"";
 return <><div className="play-grid"><div>
  {data.pendingReveal&&<div className="notice"><strong>Episode {data.pendingReveal.id} results are spoiler-protected.</strong><span>Scores and eliminations reveal automatically {new Date(data.pendingReveal.revealAt).toLocaleString("en-US",{weekday:"long",hour:"numeric",minute:"2-digit",timeZone:"America/Detroit"})} ET.</span></div>}
  {data.pick?.carriedFromEpisodeId&&<div className="notice"><strong>Your Episode {data.pick.carriedFromEpisodeId} picks carried forward automatically.</strong><span>Eligible choices are already saved for Episode {data.episode.id}. Review or change them before the deadline; choices that are no longer valid were left open.</span></div>}
  <div className="notice"><strong>Two core picks are required.</strong><span>Vote-out and wild-card predictions are optional chances to score more.</span></div>
  <section className="panel"><div className="panel-title"><div><p className="eyebrow">1 point · +1 underdog bonus</p><h2>Your favorite castaway</h2></div><span className="status-pill">{favorite?"Selected":"Needed"}</span></div><p className="pick-help">Favorites are shareable. If fewer than 20% of submitted favorites back yours and they are not voted out, you earn an extra point.</p><div className="pick-options">{data.castaways.map(c=><div className={`pick-option ${c.tribe.toLowerCase()}`} key={c.id}><input aria-label={`Choose ${c.name} as your favorite`} disabled={data.locked} checked={favorite===c.id} onChange={()=>setFavorite(c.id)} id={`fav-${c.id}`} name="favorite" type="radio"/><label aria-label={`Choose ${c.name} as your favorite`} htmlFor={`fav-${c.id}`}><span className="avatar"><img src={c.image} alt=""/></span><span><strong>{c.name}</strong><small>{c.tribe}</small></span></label></div>)}</div></section>
  <section className="panel prediction-panel"><div className="panel-title"><div><p className="eyebrow">2 points</p><h2>Who wins {data.episode.phase==="individual"?"individual":"tribal"} immunity?</h2></div><span className="status-pill">{immunity?"Selected":"Needed"}</span></div>{data.episode.phase==="individual"?<CastSelect id="immunity" value={immunity} setValue={setImmunity} cast={data.castaways} disabled={data.locked}/>:<div className="tribe-picks">{["Savu","Toka"].map(t=><div className={`tribe-choice ${t.toLowerCase()}`} key={t}><input disabled={data.locked} checked={immunity===t} onChange={()=>setImmunity(t)} id={`tribe-${t}`} name="immunity" type="radio"/><label htmlFor={`tribe-${t}`}><small>TRIBE</small><h3>{t}</h3></label></div>)}</div>}</section>
  <div className="prediction-grid"><section className="panel"><p className="eyebrow">Optional · 3 points</p><h2>Who is voted out?</h2><CastSelect id="boot" value={boot} setValue={setBoot} cast={data.castaways} disabled={data.locked}/></section><section className="panel"><p className="eyebrow">Optional · 1 point</p><h2>{data.episode.bonusQuestion}</h2><div className="bonus-options">{data.episode.bonusOptions.map(o=><button type="button" disabled={data.locked} className={bonus===o?"selected":""} onClick={()=>setBonus(bonus===o?"":o)} key={o}>{o}</button>)}</div></section></div>
  <section className="panel season-picks"><div><p className="eyebrow">Preseason pick · 10 points to win · 3 to make finale</p><h2>Your Sole Survivor</h2><p>{data.preseasonLocked&&!data.profile?.winnerPick?"The preseason window has closed.":"You can change this until Episode 1 locks."}</p></div><CastSelect id="winner" value={winner} setValue={setWinner} cast={data.castaways} disabled={data.preseasonLocked}/></section>
  <section className="panel double-card"><div><p className="eyebrow">One use all season</p><h2>Double Down</h2><p>Double one correct prediction this week. Saving a selection spends the token when picks lock.</p></div><select aria-label="Double Down prediction" disabled={data.locked||(!data.doubleDownAvailable&&!doubleDown)} value={doubleDown} onChange={e=>setDoubleDown(e.target.value)}><option value="">Save it for later</option><option value="immunity">Immunity pick</option><option value="boot">Vote-out pick</option><option value="bonus">Bonus prediction</option></select></section>
  <div className="save-bar sticky-save"><span className={`save-message ${saveConfirmation&&!dirty?"save-success":""}`} role="status" aria-live="polite">{error?<strong>{error}</strong>:lastSavedAt?<><strong>{dirty?"Unsaved changes":saveConfirmation?"✓ Picks saved successfully":"Picks on file"}</strong><small>{savedLabel}</small></>:!complete?(data.preseasonLocked?"Choose your favorite and immunity pick to save.":"Choose your favorite, immunity pick, and Sole Survivor to save."):"Picks stay private until the deadline."}</span><button className="button button-primary" onClick={save} disabled={saving||data.locked||!complete}>{saving?"Saving…":data.locked?"Picks locked":saveConfirmation&&!dirty?"Saved ✓":"Save picks"}</button></div>
 </div><aside><div className="deadline-box"><p className="eyebrow">Picks lock in</p><Countdown target={data.episode.lockAt}/><p>{new Date(data.episode.lockAt).toLocaleString("en-US",{weekday:"long",month:"long",day:"numeric",hour:"numeric",minute:"2-digit",timeZone:"America/Detroit"})} ET</p></div><div className="panel leaderboard"><p className="eyebrow">Live standings</p><h2>Leaderboard</h2>{data.leaderboard.map(row=><div className="score-row" key={`${row.rank}-${row.name}`}><span className="rank">{String(row.rank).padStart(2,"0")}</span><span className="avatar small" aria-label={`${profileIcon(row.avatarKey).label} icon`}>{profileIcon(row.avatarKey).symbol}</span><span><strong>{row.teamName||row.name}</strong>{row.badges[0]&&<small className="badge">{row.badges[0]}</small>}</span><span className="score">{row.points}</span></div>)}</div>
  <div className="panel matchup"><p className="eyebrow">This week’s points</p><h2>Score comparisons</h2>{data.matchups.map((m,i)=><div className="versus" key={i}><span>{m.a.name}<strong>{m.a.points}</strong></span><i>VS</i><span>{m.b?.name||"No comparison"}<strong>{m.b?.points??"—"}</strong></span></div>)}</div>
  {data.locked&&data.pickPercentages&&<div className="panel pulse"><p className="eyebrow">League pulse</p><h2>What everyone picked</h2>{[["Favorite","favorite_id"],["Immunity","immunity_pick"],["Going home","boot_pick"]].map(([label,key])=><div key={key}><h3>{label}</h3>{data.pickPercentages![key].slice(0,4).map(p=><div className="percent-row" key={p.value}><span>{name(p.value)}</span><strong>{p.percent}%</strong></div>)}</div>)}</div>}
 </aside></div></>
}
function CastSelect({id,value,setValue,cast,disabled}:{id:string;value:string;setValue:(v:string)=>void;cast:Castaway[];disabled:boolean}){return <select className="cast-select" id={id} value={value} onChange={e=>setValue(e.target.value)} disabled={disabled}><option value="">Choose a castaway…</option>{cast.map(c=><option value={c.id} key={c.id}>{c.name} · {c.tribe}</option>)}</select>}
function JoinForm({onJoined}:{onJoined:()=>Promise<void>}){const[name,setName]=useState(""),[team,setTeam]=useState(""),[inviteCode,setInviteCode]=useState(""),[busy,setBusy]=useState(false),[joinError,setJoinError]=useState("");async function join(e:React.FormEvent){e.preventDefault();setBusy(true);setJoinError("");const response=await fetch("/api/league",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({displayName:name,teamName:team,inviteCode})});setBusy(false);if(!response.ok){const body=await response.json().catch(()=>({}));setJoinError(body.error||"The league could not be joined. Try again.");return}await onJoined()}return <form className="join-card" onSubmit={join}><p className="eyebrow">One last step</p><h2>Join the family league</h2><p>Use the account you just created and the invite code Mike shared. Your picks stay private until the episode locks. Joining also signs you up for one spoiler-free picks reminder the day before each new episode.</p>{joinError&&<div className="notice">{joinError}</div>}<label htmlFor="name">Your name</label><input id="name" required maxLength={40} value={name} onChange={e=>setName(e.target.value)} placeholder="Mike"/><label htmlFor="team">Team name <small>(optional)</small></label><input id="team" maxLength={50} value={team} onChange={e=>setTeam(e.target.value)} placeholder="The Torch Snuffers"/><label htmlFor="invite-code">League invite code</label><input id="invite-code" required maxLength={40} autoCapitalize="characters" value={inviteCode} onChange={e=>setInviteCode(e.target.value)} placeholder="Enter invite code"/><button className="button button-primary" disabled={busy}>{busy?"Joining…":"Join league →"}</button></form>}
