import type { Metadata } from "next";
import { AppShell } from "../components/AppShell";

export const metadata:Metadata={title:"Rules"};

const rules=[
 ["01","Opening Outlast Pick","Before Episode 1 locks, choose one castaway to reach the individual game. This is not a preseason winner pick. You may change it until the Episode 1 deadline, and the name shown as your Opening Outlast Pick is the selection that will count."],
 ["02","When the individual game begins","The trigger is the moment Jeff officially announces there are no more tribes and the game is individual. If your Opening Outlast Pick is still in the game at that announcement, you earn 10 points. You still earn the 10 points if that castaway is voted out later in the same episode. If your pick left before the announcement, you earn 0 points."],
 ["03","One Final Torch decision","After that episode’s spoiler-safe results reveal, one decision window opens for everyone. Keep your original active castaway to remain eligible for 10 points if they win or 3 points if they finish in the final three. Switch to any remaining castaway to receive half of those awards: 5 points to win or 1.5 points for the final three. Switching never removes the individual-game points you already earned. If your original pick is gone, you may still switch for the half-point awards. The Final Torch Pick locks with the following episode’s normal pick deadline and never reopens."],
 ["04","Weekly Favorite Pick","Choose one active castaway to survive that episode. If they are not voted out, earn 1 point—even if they leave for medical or personal reasons. If fewer than 20% of submitted Weekly Favorite Picks chose the same castaway and they survive, earn a 1-point underdog bonus."],
 ["05","Weekly Immunity Pick","Before the individual game is confirmed, choose the tribe that will win immunity. After it is confirmed, choose the individual castaway who will win. A correct pick earns 2 points. If the show unexpectedly changes formats after picks lock, that episode’s incompatible immunity prediction is void and does not break an existing streak."],
 ["06","Required Vote-Out Pick","Choose the castaway you believe will be voted out at Tribal Council. A correct pick earns 3 points. This pick is required each week. An incorrect pick earns 0 points. Medical removals and quits do not count as vote-outs."],
 ["07","Optional Play Your Advantage","Answer a new question based on the official episode previews each week. Watching the previews can give you an edge. When there is no suitable preview question, the default is “Will an idol be played?” A correct answer earns 1 point; a wrong answer loses 1 point. Skip for 0 points with no risk. Choose fresh each week: Play Your Advantage answers do not carry forward."],
 ["08","Immunity streak and Shot in the Dark","Three consecutive correct Immunity Picks earn a 2-point streak bonus. Once per season, you may play your Shot in the Dark on an Immunity Pick, Vote-Out Pick, or Play Your Advantage answer. If that selected prediction is correct, you earn its normal points a second time. An incorrect Play Your Advantage answer still costs only 1 point. A saved Shot in the Dark is spent when that episode locks, and it never carries forward automatically."],
 ["09","Automatic weekly carryover","If you miss a week, each prior weekly pick that is still eligible carries into the next episode. Eliminated castaways, incompatible immunity formats, and the Shot in the Dark are left open. Play Your Advantage answers never carry forward because they risk a point. They stay skipped for 0 points unless you choose an answer for that episode. Always check the labels on the Play page to see exactly which selections are on file."],
 ["10","Deadlines and pick privacy","Weekly selections lock exactly one hour before the scheduled episode airtime. You may edit and resave freely before the deadline; server time is final. Picks remain private from other players until the deadline passes."],
 ["11","Spoiler protection","The commissioner may enter results after the episode, but scores, eliminations, the leaderboard, and the Final Torch decision remain hidden until 9:00 AM ET the following morning. The Campfire also pauses posting and voting during that spoiler window."],
 ["12","My Season and the leaderboard","One running score covers the whole season. Weekly points and bonuses, Opening Outlast awards, and Final Torch awards all add to the same total. Your points carry forward through the merge and finale. My Season shows your published episode picks, point breakdowns, weekly ranks, and movement on the leaderboard. Equal scores share a rank, and a tie for the season title produces joint champions."],
 ["13","Campfire ideas, replies, and voting","Start a main Campfire idea or reply beneath an existing one. Replies stay attached to that idea in chronological order and do not compete in the main ranking. Every league member may upvote or downvote each main idea once and may change or remove that vote. Tribe Score equals upvotes minus downvotes. A popular idea becomes an official rule only after the commissioner adds it to this Rules page."],
 ["14","Private Messages · Whisper Network","Private Messages are one-to-one conversations between joined league members. Only the sender and recipient may load a conversation through the application. Unread counts appear beside Messages in the navigation, and opening a conversation marks incoming messages as read. The Campfire remains the place for ideas the whole league should see."],
] as const;

export default function RulesPage(){return <AppShell><main className="wrap interior-page rules-page"><header className="page-hero"><p className="eyebrow">Outlast 51 rulebook</p><h1>Know every move.</h1><p>Every pick has a name, a deadline, and a clear scoring result. Check the Play page before lock to confirm exactly who—or what—you selected.</p></header><section className="rules-quickstart" aria-labelledby="quickstart-title"><div><p className="eyebrow">Ready in 30 seconds</p><h2 id="quickstart-title">Your weekly checklist</h2></div><ol><li><strong>Make three weekly picks.</strong> Choose a Favorite, an Immunity winner, and a Vote-Out Pick. Before Episode 1, also save your Opening Outlast Pick.</li><li><strong>Add a prediction if you want.</strong> Play Your Advantage is optional: +1 correct, −1 wrong, or 0 if skipped. Your Shot in the Dark can double one correct prediction once all season.</li><li><strong>Save before the deadline.</strong> Picks lock one hour before airtime. Check for the saved confirmation; results appear after 9:00 AM ET the next morning.</li></ol><a className="button button-primary" href="/play">Make my picks →</a><p>When the individual game begins, the Play page will guide you through your one-time Final Torch decision.</p></section><div className="rules-layout"><div className="rules-main">{rules.map(([number,heading,copy])=><section className="rule" key={number}><span>{number}</span><div><h2>{heading}</h2><p>{copy}</p></div></section>)}</div><aside className="rules-sidebar"><div className="points-card"><p className="eyebrow">Weekly points</p><div><span>Favorite survives</span><strong>+1</strong></div><div><span>Underdog favorite</span><strong>+1</strong></div><div><span>Correct immunity</span><strong>+2</strong></div><div><span>Correct vote-out</span><strong>+3</strong></div><div><span>Correct Play Your Advantage</span><strong>+1</strong></div><div><span>Wrong Play Your Advantage</span><strong>−1</strong></div><div><span>Skip Play Your Advantage</span><strong>0</strong></div><div><span>3-pick immunity streak</span><strong>+2</strong></div><p className="tiny">Shot in the Dark repeats the points from one correct prediction once per season.</p></div><div className="points-card season-points-card"><p className="eyebrow">Season picks</p><div><span>Reach individual game</span><strong>+10</strong></div><div><span>Original pick wins</span><strong>+10</strong></div><div><span>Original reaches final 3</span><strong>+3</strong></div><div><span>Switched pick wins</span><strong>+5</strong></div><div><span>Switched reaches final 3</span><strong>+1.5</strong></div></div></aside></div></main></AppShell>}
