import type { Metadata } from "next";import { AppShell } from "../components/AppShell";export const metadata:Metadata={title:"Rules"};
const rules=[
 ["01","Favorite castaway","Choose any active castaway each week. If they are not voted out, earn 1 point—even if they leave for medical or personal reasons. Favorites are shareable. If fewer than 20% of submitted favorites selected yours and they stay, earn a 1-point underdog bonus."],
 ["02","Immunity prediction","Before the merge, pick the tribe that wins immunity. After the merge, pick the individual winner. A correct prediction earns 2 points."],
 ["03","Optional vote-out prediction","Predict the castaway who is voted out that episode. A correct call earns 3 points; medical removals and quits do not count. You can save without making this pick."],
 ["04","Optional weekly wild card","Answer the commissioner’s changing yes/no or multiple-choice question. A correct answer earns 1 point, and skipping it does not block your core picks."],
 ["05","Streaks & Double Down","Three consecutive correct immunity predictions earn a 2-point streak bonus. Once per season, Double Down one immunity, vote-out, or wild-card prediction to earn its points a second time."],
 ["06","Sole Survivor pick","Before Episode 1 locks, choose the season winner. Earn 10 points if correct or 3 points if that player reaches the finale."],
 ["07","Automatic weekly carryover","If you miss a week, every prior choice that is still eligible automatically carries forward. Eliminated castaways and picks that no longer fit the immunity format are left open. Double Down never carries automatically."],
 ["08","The lock","All selections lock exactly one hour before airtime and stay hidden from everyone else until then. You may edit freely before the deadline; server time is final."],
 ["09","Spoiler protection","The commissioner can enter results after the show, but scores, eliminations, and leaderboard changes remain hidden until 9:00 AM ET the following morning."],
];
export default function RulesPage(){return <AppShell><main className="wrap interior-page rules-page"><header className="page-hero"><p className="eyebrow">League rules</p><h1>More ways to make the read.</h1><p>Weekly picks reward consistency, while bold calls, streaks, and a well-timed Double Down can move the leaderboard fast.</p></header><div className="rules-layout"><div className="rules-main">{rules.map(([n,h,p])=><section className="rule" key={n}><span>{n}</span><div><h2>{h}</h2><p>{p}</p></div></section>)}</div><aside className="points-card"><p className="eyebrow">Weekly points</p><div><span>Favorite survives</span><strong>+1</strong></div><div><span>Underdog favorite</span><strong>+1</strong></div><div><span>Correct immunity</span><strong>+2</strong></div><div><span>Correct vote-out</span><strong>+3</strong></div><div><span>Wild card</span><strong>+1</strong></div><div><span>3-week streak</span><strong>+2</strong></div><p className="tiny">Double Down can add up to 3 more points once per season. Picks remain private until lock.</p></aside></div></main></AppShell>}
