import { getChatGPTUser } from "../../chatgpt-auth";
import { createAdminClient } from "../../../lib/supabase/admin";
import { ensureDatabase,publishDueResults } from "../../../db/runtime";

async function spoilerWindow(){const db=createAdminClient(),now=new Date().toISOString();const {data}=await db.from("episodes").select("reveal_at").lte("air_at",now).gt("reveal_at",now).order("id",{ascending:false}).limit(1).maybeSingle();return data}
async function joinedUser(){const user=await getChatGPTUser();if(!user)return null;const {data}=await createAdminClient().from("profiles").select("league_joined_at").eq("id",user.userId).maybeSingle();return data?.league_joined_at?user:null}

export async function GET(){const user=await joinedUser();if(!user)return Response.json({error:"Join the league first"},{status:403});await ensureDatabase();await publishDueResults();const db=createAdminClient(),locked=await spoilerWindow();const {data:posts,error}=await db.from("posts").select("id,body,created_at,user_id").order("created_at",{ascending:false}).limit(50);if(error)return Response.json({error:"Campfire unavailable"},{status:500});const ids=[...new Set((posts||[]).map(p=>p.user_id))],{data:profiles}=ids.length?await db.from("profiles").select("id,display_name,team_name,avatar_key").in("id",ids):{data:[]};const names=new Map((profiles||[]).map(p=>[p.id,p]));return Response.json({posts:(posts||[]).map(p=>({id:p.id,body:p.body,createdAt:p.created_at,name:names.get(p.user_id)?.display_name||"Player",teamName:names.get(p.user_id)?.team_name||"",avatarKey:names.get(p.user_id)?.avatar_key||"torch"})),locked:!!locked,revealAt:locked?.reveal_at||null})}
export async function POST(request:Request){const user=await joinedUser();if(!user)return Response.json({error:"Join the league first"},{status:403});await ensureDatabase();await publishDueResults();const locked=await spoilerWindow();if(locked)return Response.json({error:"Campfire posting reopens after the 9:00 AM spoiler reveal",revealAt:locked.reveal_at},{status:409});const body=await request.json() as {body?:string},text=body.body?.trim().slice(0,500);if(!text)return Response.json({error:"Write a message first"},{status:400});const {error}=await createAdminClient().from("posts").insert({user_id:user.userId,body:text,created_at:new Date().toISOString()});return error?Response.json({error:"That message could not be posted"},{status:500}):Response.json({ok:true})}
