"use client";

import { useEffect,useState } from "react";
import { profileIcon } from "../profile-icons";

type Post={id:number;body:string;createdAt:string;name:string;teamName:string;avatarKey:string;upvotes:number;downvotes:number;score:number;myVote:-1|0|1};

export function CampfireClient(){
 const[posts,setPosts]=useState<Post[]>([]),[body,setBody]=useState(""),[busy,setBusy]=useState(false),[votingPost,setVotingPost]=useState<number|null>(null),[locked,setLocked]=useState(false),[revealAt,setRevealAt]=useState<string|null>(null),[error,setError]=useState("");
 const load=()=>fetch("/api/posts").then(async response=>{const data=await response.json();if(!response.ok){setError(data.error||"The Campfire could not load.");return}setPosts(data.posts||[]);setLocked(Boolean(data.locked));setRevealAt(data.revealAt||null)});
 useEffect(()=>{load()},[]);

 async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError("");const response=await fetch("/api/posts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({body})}),output=await response.json();setBusy(false);if(response.ok){setBody("");await load()}else setError(output.error||"That message could not be posted.")}
 async function vote(post:Post,nextVote:-1|1){setVotingPost(post.id);setError("");const voteValue=post.myVote===nextVote?0:nextVote,response=await fetch("/api/posts",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({postId:post.id,vote:voteValue})}),output=await response.json();setVotingPost(null);if(response.ok)await load();else setError(output.error||"Your vote could not be counted.")}

 return <><div className="campfire-banner"><span aria-hidden="true">🔥</span><div><p className="eyebrow">The tribe shapes the game</p><h2>Pitch a twist. Vote on the ideas.</h2><p>Upvote ideas you want added and downvote the ones you would pass on. Posts with the highest Tribe Score rise to the top for the commissioner to review.</p></div></div><div className="notice"><strong>Spoiler-safe Campfire</strong><span>{locked&&revealAt?`Posting and voting reopen ${new Date(revealAt).toLocaleString("en-US",{weekday:"long",hour:"numeric",minute:"2-digit",timeZone:"America/Detroit"})} ET.`:"Keep future-episode spoilers away from the fire."}</span></div>{error&&<div className="notice campfire-error" role="alert"><strong>{error}</strong></div>}<div className="campfire-layout"><form className="panel post-box" onSubmit={submit}><label htmlFor="post">Bring an idea to the fire</label><p>Suggest a rule, scoring twist, challenge, or anything that could make the league more fun.</p><textarea id="post" maxLength={500} required disabled={locked} value={body} onChange={event=>setBody(event.target.value)} placeholder={locked?"The Campfire is quiet during the spoiler window.":"My idea for the game is…"}/><div><small>{body.length}/500</small><button className="button button-primary" disabled={busy||locked}>{busy?"Posting…":locked?"Spoiler window":"Post to the Campfire"}</button></div></form><section className="post-feed" aria-label="Campfire ideas and comments">{posts.length?posts.map(post=><article className="post" key={post.id}><div className="avatar small" aria-label={`${profileIcon(post.avatarKey).label} icon`}>{profileIcon(post.avatarKey).symbol}</div><div><header><strong>{post.teamName||post.name}</strong><time>{new Date(post.createdAt).toLocaleString("en-US",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</time></header><p>{post.body}</p><div className="post-votes"><span className="tribe-score"><small>Tribe Score</small><strong>{post.score>0?`+${post.score}`:post.score}</strong></span><button type="button" aria-label={`Upvote post by ${post.teamName||post.name}`} aria-pressed={post.myVote===1} className={post.myVote===1?"voted":""} disabled={locked||votingPost===post.id} onClick={()=>vote(post,1)}><span aria-hidden="true">▲</span> Upvote <strong>{post.upvotes}</strong></button><button type="button" aria-label={`Downvote post by ${post.teamName||post.name}`} aria-pressed={post.myVote===-1} className={post.myVote===-1?"voted down":""} disabled={locked||votingPost===post.id} onClick={()=>vote(post,-1)}><span aria-hidden="true">▼</span> Downvote <strong>{post.downvotes}</strong></button></div></div></article>):<div className="notice">The Campfire is quiet. Bring the first idea to the fire.</div>}</section></div></>;
}
