import { carryForwardPicks } from "./pick-carryover";
import { createAdminClient } from "../lib/supabase/admin";
import { ensureDatabase, publishDueResults, revealAtForAirTime } from "./runtime";

export type EpisodeScheduleInput={episodeId:number;title:string;airAt:string|Date;phase:"tribe"|"individual";bonusQuestion:string;bonusOptions:string[]};
export async function scheduleEpisode(input:EpisodeScheduleInput){
 const id=Number(input.episodeId),title=String(input.title||"").trim().slice(0,120),airAt=new Date(input.airAt),phase=input.phase==="individual"?"individual":"tribe",bonusQuestion=String(input.bonusQuestion||"").trim().slice(0,140),bonusOptions=[...new Set((input.bonusOptions||[]).map(x=>String(x).trim().slice(0,40)).filter(Boolean))];
 if(!id||id<1||!title||Number.isNaN(airAt.getTime())||!bonusQuestion||bonusOptions.length<2||bonusOptions.length>4)return{ok:false as const,status:400,error:"Complete the schedule and provide two to four bonus choices"};
 await ensureDatabase();const db=createAdminClient();const {data:existing}=await db.from("episodes").select("phase,bonus_question,bonus_options,results_posted").eq("id",id).maybeSingle();const {count}=existing?await db.from("picks").select("id",{count:"exact",head:true}).eq("episode_id",id):{count:0};const choicesChanged=existing&&(existing.phase!==phase||existing.bonus_question!==bonusQuestion||JSON.stringify(existing.bonus_options)!==JSON.stringify(bonusOptions));if(existing?.results_posted&&choicesChanged)return{ok:false as const,status:409,error:"That episode already has results, so its scoring fields are frozen"};if((count||0)>0&&choicesChanged)return{ok:false as const,status:409,error:"Picks already exist, so the immunity format and bonus question are frozen"};
 const lockAt=new Date(airAt.getTime()-3600000).toISOString(),revealAt=revealAtForAirTime(airAt);const {error}=await db.from("episodes").upsert({id,season:51,title,air_at:airAt.toISOString(),lock_at:lockAt,reveal_at:revealAt,phase,bonus_question:bonusQuestion,bonus_options:bonusOptions,results_posted:existing?.results_posted||false,results_published:false,updated_at:new Date().toISOString()});if(error)throw error;await publishDueResults();const carried=await carryForwardPicks(id);return{ok:true as const,episodeId:id,title,airAt:airAt.toISOString(),lockAt,revealAt,phase,bonusQuestion,bonusOptions,carried};
}
