"use client";
import { useEffect,useState } from "react";

type Episode={id:number;title:string;phase:string;bonusQuestion:string;bonusOptions:string;revealAt:string;resultsPosted:number;resultsPublished:number};
type Cast={id:string;name:string;tribe:string};
type AdminData={episodes:Episode[];castaways:Cast[]};

export function AdminClient(){
 const[data,setData]=useState<AdminData|null>(null),[msg,setMsg]=useState("");const load=()=>fetch("/api/admin").then(r=>r.json()).then(setData);useEffect(()=>{load()},[]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setMsg("Saving…");const body=Object.fromEntries(new FormData(e.currentTarget).entries()) as Record<string,FormDataEntryValue>;if(body.action==="schedule"&&body.airAt)body.airAt=new Date(String(body.airAt)).toISOString();const r=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),out=await r.json();if(r.ok){const reveal=out.revealAt?new Date(out.revealAt).toLocaleString("en-US",{weekday:"long",month:"short",day:"numeric",hour:"numeric",minute:"2-digit",timeZone:"America/Detroit"}):"";setMsg(out.published?"Saved and published.":reveal?`Saved privately. It will publish automatically ${reveal} ET.`:"Saved successfully.");await load()}else setMsg(out.error)}
 if(!data)return <p>Loading controls…</p>;const open=data.episodes.filter(e=>!e.resultsPosted);
 return <><p className="notice">{msg||"AI commissioner is active. Weekly schedules and bonus questions are prepared automatically; results stay private until 9:00 AM ET the next morning."}</p><div className="commissioner-grid">
 <form className="admin-card" onSubmit={submit}><input type="hidden" name="action" value="schedule"/><h2>Schedule episode</h2><p>Picks lock one hour before airtime. Results reveal at 9:00 AM ET the next day.</p><label>Episode number<input name="episodeId" type="number" min="1" required/></label><label>Title<input name="title" required placeholder="Episode 2"/></label><label>Airtime<input name="airAt" type="datetime-local" required/></label><label>Phase<select name="phase"><option value="tribe">Tribe immunity</option><option value="individual">Individual immunity</option></select></label><label>Bonus question<input name="bonusQuestion" required placeholder="Will an idol be played?"/></label><label>Choices, separated by |<input name="bonusOptions" required defaultValue="Yes | No"/></label><button className="button button-primary">Save schedule</button></form>
 <form className="admin-card" onSubmit={submit}><input type="hidden" name="action" value="results"/><h2>Enter results privately</h2><p>Scores are calculated now but remain hidden until the episode’s 9:00 AM reveal.</p><label>Episode<select name="episodeId" required><option value="">Choose…</option>{open.map(e=><option key={e.id} value={e.id}>{e.id} · {e.title}</option>)}</select></label><label htmlFor="booted">Castaway who left</label><CastSelect id="booted" name="booted" cast={data.castaways}/><label>Immunity winner<select name="immunityWinner" required><option value="">Choose…</option><option>Savu</option><option>Toka</option>{data.castaways.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Bonus answer<select name="bonusAnswer" required><option value="">Choose…</option>{Array.from(new Set(open.flatMap(e=>{try{return JSON.parse(e.bonusOptions)}catch{return[]}}))).map(x=><option key={String(x)}>{String(x)}</option>)}</select></label><button className="button button-primary">Save private results</button></form>
 <form className="admin-card" onSubmit={submit}><input type="hidden" name="action" value="finale"/><h2>Enter finale privately</h2><p>Winner points follow the finale episode’s scheduled 9:00 AM reveal.</p><label>Finale episode<select name="episodeId" required><option value="">Choose…</option>{data.episodes.map(e=><option key={e.id} value={e.id}>{e.id} · {e.title}</option>)}</select></label><label htmlFor="winner">Sole Survivor</label><CastSelect id="winner" name="winner" cast={data.castaways}/><label htmlFor="finalist2">Second finalist</label><CastSelect id="finalist2" name="finalist2" cast={data.castaways}/><label htmlFor="finalist3">Third finalist</label><CastSelect id="finalist3" name="finalist3" cast={data.castaways}/><button className="button button-primary">Save private finale</button></form>
 </div></>}

function CastSelect({id,name,cast}:{id:string;name:string;cast:Cast[]}){return <select id={id} name={name} required><option value="">Choose…</option>{cast.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>}
