-- Keep Campfire replies attached to their original idea and add private
-- one-to-one messages for joined league members.
alter table public.posts
  add column parent_post_id bigint references public.posts(id) on delete cascade;

create index idx_posts_parent_created
on public.posts(parent_post_id, created_at)
where parent_post_id is not null;

create table public.private_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references auth.users(id) on delete cascade,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 1000),
  read_at timestamptz,
  created_at timestamptz not null default now(),
  constraint private_messages_different_players check (sender_id <> recipient_id)
);

create index idx_private_messages_sender_recipient
on public.private_messages(sender_id, recipient_id, created_at desc);

create index idx_private_messages_recipient_sender
on public.private_messages(recipient_id, sender_id, created_at desc);

create index idx_private_messages_unread
on public.private_messages(recipient_id, created_at desc)
where read_at is null;

alter table public.private_messages enable row level security;
revoke all on public.private_messages from anon, authenticated;
grant select, insert, update, delete on public.private_messages to service_role;
grant usage, select on sequence public.private_messages_id_seq to service_role;
