-- Clean Season 51 platform for Vercel + Supabase.
-- Episode outcomes live separately from the public schedule so direct Data API
-- access cannot reveal spoilers before the application publishes them.

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  team_name text not null default '',
  is_admin boolean not null default false,
  total_points integer not null default 0,
  winner_pick text,
  preseason_points integer not null default 0,
  immunity_streak integer not null default 0,
  longest_streak integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.episodes (
  id integer primary key,
  season integer not null default 51 check (season = 51),
  title text not null,
  air_at timestamptz not null,
  lock_at timestamptz not null,
  reveal_at timestamptz not null,
  phase text not null default 'tribe' check (phase in ('tribe','individual')),
  bonus_question text not null,
  bonus_options jsonb not null default '["Yes","No"]'::jsonb,
  results_posted boolean not null default false,
  results_published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.episode_results (
  episode_id integer primary key references public.episodes(id) on delete cascade,
  departures jsonb not null default '[]'::jsonb,
  immunity_winners jsonb not null default '[]'::jsonb,
  immunity_void boolean not null default false,
  bonus_answer text not null,
  finale_winner text,
  finalists jsonb not null default '[]'::jsonb,
  recorded_at timestamptz not null default now()
);

create table public.picks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  episode_id integer not null references public.episodes(id) on delete cascade,
  favorite_id text not null default '',
  immunity_pick text not null default '',
  boot_pick text not null default '',
  bonus_pick text not null default '',
  double_down text not null default '' check (double_down in ('','immunity','boot','bonus')),
  carried_from_episode_id integer references public.episodes(id),
  favorite_point integer not null default 0,
  immunity_point integer not null default 0,
  boot_point integer not null default 0,
  bonus_point integer not null default 0,
  underdog_point integer not null default 0,
  streak_point integer not null default 0,
  double_point integer not null default 0,
  updated_at timestamptz not null default now(),
  unique(user_id, episode_id)
);

create table public.cast_status (
  castaway_id text primary key,
  status text not null default 'active' check (status in ('active','eliminated')),
  updated_at timestamptz not null default now()
);

create table public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 500),
  created_at timestamptz not null default now()
);

create table public.invites (
  id uuid primary key default gen_random_uuid(),
  email text not null,
  token_hash text not null unique,
  created_by uuid not null references auth.users(id) on delete cascade,
  expires_at timestamptz not null,
  accepted_at timestamptz,
  created_at timestamptz not null default now()
);

create index idx_episodes_open on public.episodes(results_posted,id);
create index idx_episodes_reveal on public.episodes(results_posted,results_published,reveal_at);
create index idx_picks_episode on public.picks(episode_id);
create index idx_picks_user on public.picks(user_id,episode_id desc);
create index idx_profiles_points on public.profiles(total_points desc);
create index idx_posts_created on public.posts(created_at desc);
create index idx_invites_email on public.invites(lower(email));

alter table public.profiles enable row level security;
alter table public.episodes enable row level security;
alter table public.episode_results enable row level security;
alter table public.picks enable row level security;
alter table public.cast_status enable row level security;
alter table public.posts enable row level security;
alter table public.invites enable row level security;

-- Safe, non-spoiler league information.
create policy "Authenticated profiles read" on public.profiles for select to authenticated using (true);
create policy "Schedule read" on public.episodes for select to authenticated using (true);
create policy "Cast status read" on public.cast_status for select to authenticated using (true);
create policy "Posts read" on public.posts for select to authenticated using (true);
create policy "Own post insert" on public.posts for insert to authenticated with check ((select auth.uid()) = user_id);

-- Picks remain private to their owner through the Data API. The server computes
-- locked league percentages and scoring with its non-browser service client.
create policy "Own picks read" on public.picks for select to authenticated using ((select auth.uid()) = user_id);
-- Writes go through validated server routes. Direct Data API writes are denied
-- so a browser cannot alter scoring columns, deadlines, or admin fields.

-- No authenticated policy is intentionally created for episode_results or
-- invites. Only trusted server routes may read outcomes or manage invitations.

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles(id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', split_part(coalesce(new.email,''),'@',1)));
  return new;
end;
$$;

revoke all on function public.handle_new_user() from public, anon, authenticated;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

-- The premiere is ready to be replaced when CBS publishes the final schedule.
insert into public.episodes(id,season,title,air_at,lock_at,reveal_at,phase,bonus_question,bonus_options)
values (
  1,51,'The Marooning',
  '2026-09-24 00:00:00+00',
  '2026-09-23 23:00:00+00',
  '2026-09-24 13:00:00+00',
  'tribe','Will an idol or advantage be played?','["Yes","No"]'::jsonb
);
